# Generated by Django 5.1.4 on 2024-12-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'まだ始めてないよ'), ('in_progress', '頑張ってるよ'), ('completed', '達成したよ！'), ('on_hold', '休憩中...'), ('cancelled', 'やめちゃった')], default='not_started', max_length=20)),
                ('details', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.goal')),
            ],
        ),
    ]
