# Generated by Django 5.1.4 on 2024-12-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goaltag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.goal')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
            options={
                'unique_together': {('goal_id', 'tag_id')},
            },
        ),
    ]
